Iter3 load order
anoriar/gophermart pull request #1
Opened 2023-11-15 17:26 UTC by anoriar

2023-11-19 10:31 UTC, gonozov0 commented
>1 Как красиво реализовать оборачивание в транзакции на уровне сервиса? В идеале же сервис ничего не должен знать о транзакциях БД. Более того, хорошо что у нас БД, а если несколько разных систем? И где то БД а где то интеграция.
Например, метод списания баллов. 3 апроса: получение текущего баланса, добавление транзакции, обновление баланса. В идеале 2 последних действия запихнуть в транзакцию. Но самый очевидно элегантный вариант - отправлять транзакцию в метод репозитория. А создавать транзакцию в сервисе?

А какая у тебя это бизнес команда? По идее да, сервис/домен/бизнес логика/ ничего не должны знать про механизм транзакций, это все должно лечь на плечи репозитория, есть же возможность эти 3 операции реализовать в одном методе репозитория под названием, к примеру, начисление кешбэка

2023-11-19 10:47 UTC, gonozov0 requested changes
Я еше посмотрю отдельно код файлов, пока общий фидбэк по структуре кода, очень сложно понимать, что где. Ты группируешь пакеты по техническим деталям: repository, service, handlers, etc
Правильнее группировать на первом же уровне по доменам, их тут у тебя как минимум 3: users, balance (здесь же по моему мнению должен быть withdrawals и accurals), orders

Раздели, пожалуйста на верхнем уровне их, причем, если ты используешь, DI, то есть app со всеми зависимостями, то эти 3 домена и весь другой код должен расположен внутри internal/app/internal/, чтобы из main можно было импортировать только InitApp

Внутри доменов уже можно делать разбивание на: application (в твоем случае это handlers), domain (в твоем случае это processors и services, непонял смысла их разделения), repository (тут же клиент с запросами во внешннюю систему заказов)

Все ошибки, dto должны быть объявлены там же, где они используются, например, domainerrors не нужно выделять, как отдельный пакет, это очень увеличивает сложность и восприятие кода, ошибки обычно в моем коде лежат, к примеру, в users/domain/errors.go, dto - users/domain/dto.go, и так соответственно в каждом домене.

Если у тебя есть что-то общее, что может исопльзовать в нескольких доменов, то я обычно создаю пакет shared и туда все складываю, например, internal/app/internal/shared/some.go

Также не понял, зачем ты используешь общий объект бд для всех доменов, важно чтобы у каждого из доменов были свои миграции, это лучше разделять, соответственно все что касается базы, я бы клал в repository без передачи нигде sqlx.db, инициалировал бы соединения и прогонял миграции при инициализации репозитория

2023-11-19 10:47 UTC, gonozov0 commented on internal/gophermart/app/init_app.go
> +func InitializeApp(ctx context.Context, conf *config.Config) (*App, error) {
Я бы это засунул в app.go

2023-11-20 07:04 UTC, alekstet approved these changes

2023-11-20 07:05 UTC, alekstet approved these changes

2023-12-03 12:19 UTC, merged